-- Run this migration in the Supabase SQL editor once.
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  shop_id bigint not null,
  user_id bigint null,
  type text not null,
  priority text not null default 'INFO',
  title text not null,
  message text not null,
  entity_type text null,
  entity_id bigint null,
  action_target text null,
  metadata jsonb not null default '{}'::jsonb,
  dedupe_key text not null,
  is_read boolean not null default false,
  read_at timestamptz null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists notifications_shop_dedupe_active_idx
  on public.notifications (shop_id, dedupe_key) where is_active = true;
create index if not exists notifications_shop_unread_idx
  on public.notifications (shop_id, is_read, created_at desc);
create index if not exists notifications_shop_type_idx
  on public.notifications (shop_id, type, created_at desc);
create index if not exists notifications_entity_idx
  on public.notifications (entity_type, entity_id);
